# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd428e170446614c4b9b72cbbee88fd758170c2e49ca1382acd7721cfa9eb4a3669bb8ca77ffec4842dba0ffce3679eb1f9ac248b6a4a4fb2b519373ae9d82da

test:
  secret_key_base: 829914b9ad2e4aa830fb99344e1ccdea24221fd5ad5a3dbdf45dc2f5f7af0225e23b18ab036b18547bd3536015ea6fc79d2d778f798f1aada35c6946db05ad3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
